[keyboard]
bindings = [
    # https://stackoverflow.com/a/42461580
    { chars = "\u001B[13;2u", key = "Return", mods = "Shift" },
    { key = "t", mods = "Command", action = "None" },
    { key = "Minus", mods = "Control", action = "ReceiveChar" },
    { key = "Plus", mods = "Control", action = "ReceiveChar" },
]

[font]
size = 14
offset.y = 5

# XTerm darker shade
[colors.primary]
background = '#121212'
foreground = '#b0b0b0'

[colors.normal]
black   = '#1c1c1c'
red     = '#9c0000'
green   = '#009900'
# yellow  = '#999900'
yellow  = '#8A8500'
# blue    = '#0000cc'
blue    = '#4F6FAF'
magenta = '#9c009c'
# cyan    = '#009999'
cyan    = '#4FA7A7'
white   = '#d0d0d0'

[colors.bright]
black   = '#555555'
red     = '#b30000'
green   = '#00b300'
# yellow  = '#b3b300'
yellow  = '#A89A00'
# blue    = '#3a3aff'
blue    = '#6F8FD7'
magenta = '#b300b3'
# cyan    = '#00b3b3'
cyan    = '#6FC7C7'
white   = '#bfbfbf'
