[keyboard]
bindings = [
    # https://stackoverflow.com/a/42461580
    { chars = "\u001B[13;2u", key = "Return", mods = "Shift" },
    { key = "t", mods = "Command", action = "None" },
    { key = "Minus", mods = "Control", action = "ReceiveChar" },
    { key = "Plus", mods = "Control", action = "ReceiveChar" },
]

[font]
normal = { family = "JetBrains Mono NL", style = "Regular" }
bold = { family = "JetBrains Mono NL", style = "Bold" }
italic = { family = "JetBrains Mono NL", style = "Italic" }
bold_italic = { family = "JetBrains Mono NL", style = "Bold Italic" }
size = 14
offset.y = 2

[window]
opacity = 0.95

# XTerm colors
[colors.primary]
background = '#000000'
foreground = '#ffffff'

[colors.normal]
black   = '#000000'
red     = '#cd0000'
green   = '#00cd00'
yellow  = '#cdcd00'
blue    = '#0000ee'
magenta = '#cd00cd'
cyan    = '#00cdcd'
white   = '#e5e5e5'

[colors.bright]
black   = '#7f7f7f'
red     = '#ff0000'
green   = '#00ff00'
yellow  = '#ffff00'
blue    = '#5c5cff'
magenta = '#ff00ff'
cyan    = '#00ffff'
white   = '#ffffff'
