#!/bin/bash

# run powertop auto tune without touching hid devices

# check if scripts is runned as root when executed by user
if [[ "$EUID" -ne 0 ]]; then
    echo "[pt-at] failed: please run as root"
    exit
fi

# enable auto tunes
powertop --auto-tune

# turn on again hid devices
HID_DEVICES=$(ls /sys/bus/usb/drivers/usbhid | grep -oE '^[0-9]+-[0-9\.]+' | sort -u)

for i in $HID_DEVICES; do
    echo -n "Enabling " | cat - /sys/bus/usb/devices/$i/product
    echo 'on' > /sys/bus/usb/devices/$i/power/control
done
